name: Validate Check

on:
  pull_request:
    branches:
      - master

env:
  tf_version: "0.13.0"
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: "fmt"
          tf_actions_comment: true